services:
  prog-demos-frontend:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    ports:
      - "127.0.0.1:4200:4200"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=4200
    restart: unless-stopped
